# apt-secure
# Autogenerated from man page /usr/share/man/man8/apt-secure.8.gz
complete -c apt-secure -l keyring -l import -d 'no longer work with recent GnuPG versions as they use a new internal format (…'

