# pager
# Autogenerated from man page /usr/share/man/man1/pager.1.gz
complete -c pager -s d -l silent
complete -c pager -s l -l logical
complete -c pager -s e -l exit-on-eof
complete -c pager -s f -l no-pause
complete -c pager -s p -l print-over
complete -c pager -s c -l clean-print
complete -c pager -s s -l squeeze
complete -c pager -s u -l plain
complete -c pager -s n -l lines
complete -c pager -o number
complete -c pager -s h -l help
complete -c pager -s V -l version

